[package]
name = "mmo-common"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.31", features = ["serde-serialize"] }
postcard = { version = "1.0", features = ["use-std"] }
serde = "1.0"
