[package]
name = "mmo-common"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.33", features = ["serde-serialize"] }
postcard = { version = "1.1", features = ["use-std"] }
serde = { version = "1.0", features = ["derive", "rc"] }
