[package]
name = "mmo-common"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { version = "2.0.0-rc.1", features = ["serde"] }
nalgebra = { version = "0.31", features = ["serde-serialize"] }
